### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by lavenzg** [clonebench/BigCloneBench#1]
Hi, it looks like the dataset consists of many single java files without dependency packages. I am just wondering if there is any dependency files that provided so I can compile those files into bytecode? Or if you already have jar files for this benchmark? Thank you very much!

**Comment by clonebench** [comment]
BigCloneBench is built on IJaDataset by SeCold group.  This is source code craled from Google Code and SourgeForge, but not in a state that is possible to compile unfortunatly.
