### ISSUE TITLE
"the file you have requested does not exist."

### ISSUE THREAD

**Issue by helenawang** [clonebench/BigCloneBench#2]
When I followed the download links, I got "the file you have requested does not exist".
Would you please update the links so that we can get the file?

**Comment by raven4752** [comment]
I found download links [here](https://jeffsvajlenko.weebly.com/bigcloneeval.html)  valid.
However, there are many versions and I'm confused which one should I use to replicate the experimental results reported in some papers...

**Comment by qw3ry** [comment]
It seems like the links were updated today!
Somehow, the "reduced version" is the same link as the non-reduced version, though

**Comment by clonebench** [comment]
Mistake with the updated link, fixed now.  But I do recommend using the newer version of BigCloneBench available here as a h2database: https://jeffsvajlenko.weebly.com/bigcloneeval.html

It has much more data, and can be used with our evaluation framework, BigCloneEval: https://github.com/jeffsvajlenko/BigCloneEval
