### ISSUE TITLE
What database software should I use to view this data set?

### ISSUE THREAD

**Issue by SumiHui** [clonebench/BigCloneBench#3]
Such as the title，I want to know the requirements for loading this dataset for database software and versions.

Thanks....

**Comment by qw3ry** [comment]
Not sure if I understand what you are looking for exactly.

Have you tried a tool like https://dbeaver.io/?

**Comment by SumiHui** [comment]
> Not sure if I understand what you are looking for exactly.
> 
> Have you tried a tool like https://dbeaver.io/?

@qw3ry , thank you very much, this is exactly what I need.

**Comment by jeffsvajlenko** [comment]
The ERA database is in postgresql format, and can be read with psql.

I reccomend using the BigCloneEval version, which contains significantly more clones: https://jeffsvajlenko.weebly.com/bigcloneeval.html

It is in h2database format, which will be lighter to load.

**Comment by qw3ry** [comment]
@jeffsvajlenko when I tried opening the h2 db I could not find any tables or data. Maybe I used a "wrong" user or something? The file has a few GB, so thats not the issue.
Could you provide a step-by-step guide how to see/extract data?

**Comment by Hareem-E-Sahar** [comment]
@qw3ry were you able to open the database and view data?

**Comment by qw3ry** [comment]
Yes, I could. I don't remember how, though. Be aware that there are 2 databases, one containing the candidate clones of your tool(s), and another one containing the benchmark clones. IIRC you have to use different credentials for those two.

**Comment by Hareem-E-Sahar** [comment]
@qw3ry, @jeffsvajlenko  I suppose bcb.h2.db contains the benchmark clones. They are a total of 8584153. The clones we get from running 'detectClones' are the one detected by the tool.
