### ISSUE TITLE
Process to typify the clones of the big clone bench

### ISSUE THREAD

**Issue by nikitamehrotra12** [clonebench/BigCloneBench#4]
Hi,

Could you please provide details of the typifying process that you have used to assign the categories to the clone pairs. It was automated or have been done manually?

**Comment by jeffsvajlenko** [comment]
Hi.  A good description of the process is provided in the following article: https://ieeexplore.ieee.org/document/6976121.  This is behind a IEEE subscription, but if you don't have a subscription you can message me directly and I can provide a copy.

**Comment by nikitamehrotra12** [comment]
Thank you for your response.
